version: '1'
volumes: 
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWD: changeme1
      MYSQL_DATABASE: testdb1
      MYSQL_USER: dbadmin01
      MYSQL_PASSWORD: changeme2
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  
