FROM ubuntu:22.04

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y mariadb-server

EXPOSE 3306

LABEL verion="1.0"
LABEL description="MariaDB Server"

HEALTHCHECK --start-period-5m \
    CMD mariadb -e 'SELECT @@datadir;' || exit 1

CMD ["mariadbd"]